### ISSUE TITLE
Error in density.default...

### ISSUE THREAD

**Issue by shayben** [grimbough/arrayQualityMetrics#3]
When running arrayQualityMetrics on an ExpressionSet object, I get the message:

Error in density.default(newX[, i], ...) : 
  need at least 2 points to select a bandwidth automatically

Can't find any solutions online for this.

**Comment by shayben** [comment]
Found the cause, a bug on my end.

**Comment by grimbough** [comment]
Is this still an issue, or did you solve it?

**Comment by shayben** [comment]
Still an issue, thanks!

**Comment by grimbough** [comment]
I want to confirm this is happening in the density plot module, so can you try running the code below.  for the first line you should substitute in whatever your `ExpressionSet` object is called.

```
## eSet <- ExpressionSet
preparedData = prepdata(expressionset = eSet, intgroup = c(), do.logtransform = TRUE)
de = aqm.density(preparedData)
qm = list("Density" = de)
outdir = tempdir()
aqm.writereport(modules = qm, reporttitle = "My example", outdir = outdir, arrayTable = pData(eSet))
```

It will probably also be helpful if you provide a few more details.  Ideally share a saved version of your `ExpressionSet` so I can run the code myself to debug.

**Comment by shayben** [comment]
> preparedData = prepdata(expressionset = eSet, intgroup = c(), do.logtransform = TRUE)
> de = aqm.density(preparedData)
Error in density.default(newX[, i], ...) : 
  need at least 2 points to select a bandwidth automatically
> qm = list("Density" = de)
> outdir = tempdir()
> aqm.writereport(modules = qm, reporttitle = "My example", outdir = outdir, arrayTable = pData(eSet))
Error in FUN(X[[i]], ...) : 
  cannot get a slot ("id") from an object of type "closure"

[ eSet.zip](https://github.com/grimbough/arrayQualityMetrics/files/3441380/eSet.zip)

Appreciate the help!

**Comment by grimbough** [comment]
There is something odd with `GSM1403495_170611_252929710389_S01_miRNA_107_Sep09_patch_1_3` (column 154).  The signal from this array is much brighter than all the others:

```
> mean(log2(exprs(eSet)))
[1] 4.33253
> mean(log2(exprs(eSet[,154])))
[1] 10.93557
```
The package filters out values that are > the 98th percentile for the intensity of all arrays, as these tend to distort some of the plots.  however, for that array this ends up excluding every single value, and leads to the error you're seeing.  If you remove the array entirely it will generate a report successfully.

```
arrayQualityMetrics(expressionset = eSet[,-154],
outdir = "Report_for_eSet",
force = TRUE,
do.logtransform = TRUE)
```
It might be worth finding out what happened to that array, but it seems likely it should fail any QC check given the unusual intensity, so it's probably fine to exclude it already.

**Comment by shayben** [comment]
Makes sense.
Thanks for the help!
